services:
  dall-e-executor:
    build:
      context: ../../
      dockerfile: docker/executor/Dockerfile
    image: kuwa-executor
    environment:
      CUSTOM_EXECUTOR_PATH: ./image_generation/dall_e.py
      EXECUTOR_ACCESS_CODE: dall-e
      EXECUTOR_NAME: DALL-E
      EXECUTOR_IMAGE: dall-e.png # Refer to src/multi-chat/public/images
    depends_on:
      - kernel
      - multi-chat
    command: []
    volumes: [
      "~/.cache/huggingface:/root/.cache/huggingface",
    ]
    extra_hosts:
      - "localhost:host-gateway"
    restart: unless-stopped
    networks: ["backend", "frontend"]